name: Utilities

on:
  issues:
    types: [assigned]

jobs:
  create-issue-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
      - name: Create Issue Branch
        id: Create_Issue_Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo branch name
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
